[package]
name = "gptebate"
version = "1.0.0"
authors = ["Jaemin Hong <hjm0901@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
async-openai = "0.10.0"
tokio = { version = "1.26.0", features = ["rt"] }
tiktoken-rs = "0.3.2"
serde_json = "1.0"
